### ISSUE TITLE
`gpu_backend` breaks containment in subproject CMake builds

### ISSUE THREAD

**Issue by wavefunction91** [icl-utk-edu/lapackpp#23]
In cases where `lapackpp` is included as a subproject, `gpu_backend` breaks containment and can be overridden by previous enablement / discovery of a CUDA compiler (e.g. `CMAKE_CUDA_COMPILER` is defined). The offending line is [here](https://github.com/icl-utk-edu/lapackpp/blob/master/CMakeLists.txt#L536). This used to be a problem in `blaspp` as well, but has since been fixed. See logic [here](https://github.com/icl-utk-edu/blaspp/blob/master/CMakeLists.txt#L245).

In general, relying on possibly externally set variables may lead to unexpected behaviour.

**Comment by mgates3** [comment]
Makes sense. I don't remember why it was written this way, with two consecutive `if`s rather than nested `if`s.

**Comment by mgates3** [comment]
@wavefunction91 Does PR #24 resolve the issue?

**Comment by wavefunction91** [comment]
@mgates3 sorry - yes, this fixes the issue
