### ISSUE TITLE
LAPACK++ Doxygen link is broken in README.md

### ISSUE THREAD

**Issue by PTNobel** [icl-utk-edu/lapackpp#27]
Currently the link [LAPACK++ Doxygen](https://icl.bitbucket.io/lapackpp/) in the README points to `icl.bitbucket.io/lapackpp/` which is no longer online. Is there an up-to-date repository with the Doxygen build for this library?

**Comment by mgates3** [comment]
I don't know what happened, but the website is working again now. Apparently an issue at Bitbucket.
