### ISSUE TITLE
Undeclared `params` var causes build error in src/cuda/cuda_heevd.cc

### ISSUE THREAD

**Issue by ericauld** [icl-utk-edu/lapackpp#47]
src/cuda/cuda_heevd.cc fails to compile with an error on line 184: "`params` was not declared in this scope". The problem is that the `params` variable is declared in only one branch (i.e. `CUSOLVER_VERSION >= 11000`) but used in both.

My first attempt to fix was simply removing `params` from the parameter list for `cusolver_heevd` in the `CUSOLVER_VERSION < 11000` branch. But then the compiler couldn't find an appropriate overload for the call to `cusolver_heevd`.

I'm submitting a PR that fixes the issue.

**Comment by cayrols** [comment]
I just tested on our system that:

1. using `cuda-9.2.88`, the master branch does not compile.
2. using `cuda-12.1.1`, the master branch compiles.
3. using `cuda-9.2.88`, the `fix-build-error` branch from @ericauld compiles correctly.


Therefore, the PR [#48](https://github.com/icl-utk-edu/lapackpp/pull/48) been merged.

Thanks,
