### ISSUE TITLE
Failure of select functions on large inputs.

### ISSUE THREAD

**Issue by TeachRaccooon** [icl-utk-edu/lapackpp#66]
I noticed an issue with GEQR and GESDD (specifically, AllVec and SomeVec options) failing when running on matrices of large sizes ( >= 2048000000 entries, double precision).
The failure error reported is "std::bad_array_new_length."

We are using Intel MKL 2023.02, running on Intel Xeon Gold 6248R, and have 1.5 TB RAM available for us.
The runs are performed in the context of [RandLAPACK](https://github.com/BallisticLA/RandLAPACK) library, but I've isolated the calls to these particular routines in separate benchmarks, so there is no external interference that might be causing this failure.

I will report if I find out anything else.

**Comment by mgates3** [comment]
2048000000 is getting close to the 2^31 = 2147483648 limit for 32-bit integers. What m, n are you using?

LAPACK++ takes 64-bit integers, but the underlying library may be taking 32-bit integers. How are you specifying the MKL library variant to link with at configure time? Did you set `blas_int = int64`?

**Comment by TeachRaccooon** [comment]
> 2 048 000 000 is getting close to the 2^31 = 2 147 483 648 limit for 32-bit integers. What m, n are you using?
> 
> LAPACK++ takes 64-bit integers, but the underlying library may be taking 32-bit integers. How are you specifying the MKL library variant to link with at configure time? Did you set `blas_int = int64`?

I've encountered this issue when running GEQR with 1,000,000 rows and 2,048 columns; also, when running GESDD with 100,000 rows and 100,000 columns.

```
Prior to building the libraries, I specified MKL via:
export MAIN_MKL_LIBS="/nfs/home/mmelnic1/mkl/intel/oneapi/mkl/latest/lib/intel64"
export LD_LIBRARY_PATH="${MAIN_MKL_LIBS}:${LD_LIBRARY_PATH}"
export LIBRARY_PATH="${MAIN_MKL_LIBS}:${LIBRARY_PATH}"
```

I have not deliberately set `blas_int = int64`, will try this soon.
But if this was an issue, wouldn't other routines fail at the specified sizes?

**Comment by mgates3** [comment]
If using modules (at least at ICL), `module load intel-mkl` should add everything to CPATH, LIBRARY_PATH, and LD_LIBRARY_PATH.

Otherwise, Intel provides a tool to setup the environment:
```
    /path/to/intel/compilers_and_libraries_2020.4.304/linux/bin/compilervars.sh intel64
```
which further invokes the `mklvars.sh` script.

**Comment by TeachRaccooon** [comment]
Turns out that the issue was indeed in me not using `-Dblas_int=int64` when configuring BLAS++ via CMake.
I have tested the aforementioned routines after setting up the libraries properly, all works well now.
We can close the issue.

**Comment by TeachRaccooon** [comment]
Turns out that the issue was indeed in me not using -Dblas_int=int64 when configuring BLAS++ via CMake.
I have tested the aforementioned routines after setting up the libraries properly, all works well now.
We can close the issue.
