### ISSUE TITLE
CMake: CUDA Build Logic

### ISSUE THREAD

**Issue by ax3l** [icl-utk-edu/lapackpp#7]
Hi,

I am still unsure how to properly build BLAS++ & LAPACK++ for CUDA.

The logic in `CMakeLists.txt` seems to first search for cuBLAS, but then continues to search for another (host-only?) BLAS provider... which picks usually up a random OpenBLAS on the system... Can you please clarify why that would be needed and cuBLAS alone is not sufficient?

I think I should do something like this when looking at the Spack build logic:
```console
cmake -S src/blaspp -B src/blaspp-summit-build -Duse_openmp=OFF -Dgpu_backend=cuda
```
?

Can we concretely clarify the recommended lines for Summit (OLCF)?
We use these [modules and environments for WarpX](https://warpx.readthedocs.io/en/latest/install/hpc/summit.html):
```bash
module load cmake/3.20.2
module load gcc/9.3.0
module load cuda/11.3.1

# why is this needed?
module load openblas/0.3.5-omp

# compiler environment hints
export CC=$(which gcc)
export CXX=$(which g++)
export FC=$(which gfortran)
export CUDACXX=$(which nvcc)
export CUDAHOSTCXX=$(which g++)
```

~~Yet BLAS++ and then LAPACK++ do not build right now.~~ (fixed https://github.com/ECP-WarpX/WarpX/pull/3449 - as long as I `module load openblas/0.3.5-omp`)

**Comment by ax3l** [comment]
CUDA install question for @mgates3  :)

**Comment by mgates3** [comment]
@ax3l Is there an outstanding issue here, or can this be closed now?
